### PR TITLE
patient documents crud

### PR DESCRIPTION
**Pull request by DivyaPatange**

### CODE REVIEW

**Comment by kolanaveen** [comment]
@DivyaPatange Looks good to me! Could we include a filter to separate the lists of active and inactive patient documents?

**Comment by DivyaPatange** [comment]
> @DivyaPatange Looks good to me! Could we include a filter to separate the lists of active and inactive patient documents?

@kolanaveen Yes we can add filter.

**Comment by kolanaveen** [comment]
> @kolanaveen Yes we can add filter.

Okay go ahead and add filter

**Comment by DivyaPatange** [comment]
> > @kolanaveen Yes we can add filter.
> 
> Okay go ahead and add filter

@kolanaveen added filter.

**Review by kolanaveen — APPROVED** [review]

**Pull request merged**
